
#This is a template to build your own project with the e-puck2_main-processor folder as a library.
#Simply adapt the lines below to be able to compile

# Define project name here
PROJECT = BeeSim

#Define path to the e-puck2_main-processor folder
GLOBAL_PATH = ../e-puck2_main-processor

#Source files to include
CSRC += ./main.c \
		./source/process_audio.c \
		./source/process_image.c \
		./source/controller.c \
		./source/TOF_sensor.c \

#Header folders to include
INCDIR += include\

#Jump to the main Makefile
include $(GLOBAL_PATH)/Makefile